#!/bin/sh
# Docker entrypoint script to generate config.js dynamically from environment variables

# Default values
API_URL="${API_URL:-/}"
ENVIRONMENT="${ENVIRONMENT:-production}"
VERSION="${VERSION:-1.0.0}"

# Generate config.js with environment variables
cat > /usr/share/nginx/html/config.js <<EOF
// Runtime configuration - Generated by docker-entrypoint.sh
// This file is dynamically created from environment variables during container startup
window.configs = {
  // API URL - injected from API_URL environment variable
  // For Choreo deployment, this will be set to the backend service URL
  apiUrl: "${API_URL}",

  // Environment
  environment: "${ENVIRONMENT}",

  // Version
  version: "${VERSION}"
};
EOF

echo "Generated config.js with API_URL=${API_URL}"

# Execute the CMD (nginx)
exec "$@"

