import React, { useEffect, useRef, useState } from 'react'
import mermaid from 'mermaid'

// Initialize mermaid once with configuration - suppress error display
mermaid.initialize({
  startOnLoad: false,
  theme: 'default',
  securityLevel: 'loose',
  logLevel: 'fatal', // Changed to fatal to suppress error messages
  suppressErrorRendering: true, // Suppress the error diagram
  themeVariables: {
    fontSize: '14px',
    fontFamily: 'ui-sans-serif, system-ui, -apple-system, sans-serif'
  },
  flowchart: {
    useMaxWidth: true,
    htmlLabels: true,
    curve: 'basis'
  }
})

// Global cleanup function to remove Mermaid error elements
function globalCleanupMermaidErrors() {
  // Remove SVGs with error role
  document.querySelectorAll('svg[aria-roledescription="error"]').forEach(el => el.remove())

  // Remove elements containing error text
  document.querySelectorAll('body > div, body > svg').forEach(el => {
    const text = el.textContent || ''
    if (text.includes('Syntax error in text') || text.includes('mermaid version')) {
      el.remove()
    }
  })
}

// Set up a MutationObserver to catch and remove Mermaid errors as soon as they appear
if (typeof window !== 'undefined' && typeof MutationObserver !== 'undefined') {
  const observer = new MutationObserver((mutations) => {
    for (const mutation of mutations) {
      for (const node of mutation.addedNodes) {
        if (node.nodeType === Node.ELEMENT_NODE) {
          const el = node
          // Check if it's a mermaid error
          if (el.tagName === 'SVG' && el.getAttribute('aria-roledescription') === 'error') {
            el.remove()
            continue
          }
          // Check if it contains mermaid error text
          const text = el.textContent || ''
          if (text.includes('Syntax error in text') || text.includes('mermaid version')) {
            el.remove()
          }
        }
      }
    }
  })

  // Start observing when DOM is ready
  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', () => {
      observer.observe(document.body, { childList: true, subtree: true })
      globalCleanupMermaidErrors()
    })
  } else {
    observer.observe(document.body, { childList: true, subtree: true })
    globalCleanupMermaidErrors()
  }
}

// Helper function to clean and fix mermaid code
function cleanMermaidCode(chart) {
  if (!chart) return ''

  let cleanChart = chart.trim()

  // Valid diagram types that should be at the start
  const validTypes = [
    'flowchart', 'graph', 'sequenceDiagram',
    'stateDiagram-v2', 'stateDiagram', 'classDiagram',
    'pie', 'gantt', 'gitGraph', 'erDiagram'
  ]

  // Find the first line that starts with a valid diagram type
  const lines = cleanChart.split('\n')
  let startIndex = 0

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i].trim()
    if (validTypes.some(type => line.startsWith(type))) {
      startIndex = i
      break
    }
  }

  // If we found a valid start, remove everything before it
  if (startIndex > 0) {
    cleanChart = lines.slice(startIndex).join('\n').trim()
  }

  // Fix common LLM syntax errors
  cleanChart = fixCommonMermaidErrors(cleanChart)

  return cleanChart
}

// Fix common mermaid syntax errors generated by LLMs
function fixCommonMermaidErrors(chart) {
  if (!chart) return ''

  let fixed = chart

  // Pre-fix: Remove any text before the diagram type declaration
  const diagramTypeMatch = fixed.match(/(flowchart|graph|sequenceDiagram|stateDiagram-v2|stateDiagram|classDiagram|erDiagram|pie|gantt|gitGraph)/i)
  if (diagramTypeMatch && diagramTypeMatch.index > 0) {
    fixed = fixed.substring(diagramTypeMatch.index)
  }

  // Fix 0: Remove common LLM prefixes/descriptions on the first line
  const firstLinePatterns = [
    /^(Here's|Here is|Below is|The following|This is|I'll create|Let me create|Creating)[^]*?\n(flowchart|graph|sequenceDiagram|stateDiagram)/im,
    /^[^]*?\n(flowchart|graph|sequenceDiagram|stateDiagram)/im
  ]

  for (const pattern of firstLinePatterns) {
    const match = fixed.match(pattern)
    if (match && match[1]) {
      fixed = fixed.substring(fixed.indexOf(match[1]))
      break
    }
  }

  // Fix 1: Remove text descriptions that are not valid syntax
  const lines = fixed.split('\n')
  const validKeywords = [
    'flowchart', 'graph', 'sequenceDiagram', 'stateDiagram', 'classDiagram',
    'pie', 'gantt', 'gitGraph', 'erDiagram', 'subgraph', 'end', 'participant',
    'actor', 'note', 'loop', 'alt', 'else', 'opt', 'par', 'critical', 'break',
    'rect', 'style', 'linkStyle', 'classDef', 'class', 'direction', 'title', '%%',
    'activate', 'deactivate', 'autonumber', 'state', 'section'
  ]

  const filteredLines = lines.filter((line, index) => {
    const trimmed = line.trim()
    if (!trimmed) return true // Keep empty lines
    if (index === 0) return true // Keep first line (diagram type)

    // Skip obvious description lines
    if (/^(This|Here|The|Note|In this|Based on|Where|Each|Shows|Represents|Diagram|Figure)/i.test(trimmed)) {
      return false
    }

    // Keep lines with valid Mermaid syntax patterns
    const hasArrow = /-->|->|-.->|==>|--o|--x|<-->|<->|--\||o--|x--|->>|-->>|<<->>|<<-->>|~~~|--/.test(trimmed)
    const hasBrackets = /[\[\]\(\)\{\}]/.test(trimmed)
    const hasColon = trimmed.includes(':') && !trimmed.startsWith('http')
    const startsWithKeyword = validKeywords.some(kw => trimmed.toLowerCase().startsWith(kw.toLowerCase()))
    const startsWithNodeId = /^[A-Za-z_][A-Za-z0-9_]*[\s\[\(\{]/.test(trimmed) || /^[A-Za-z_][A-Za-z0-9_]*\s*-->/.test(trimmed)
    const isIndentedContent = line.startsWith('    ') || line.startsWith('\t')
    const isStateTransition = /\[\*\]/.test(trimmed) // State diagram start/end

    return hasArrow || hasBrackets || hasColon || startsWithKeyword || startsWithNodeId || isIndentedContent || isStateTransition
  })

  fixed = filteredLines.join('\n')

  // Fix 2: Fix common arrow syntax issues
  fixed = fixed.replace(/--\s+>/g, '-->') // "-- >" to "-->"
  fixed = fixed.replace(/-\s+->/g, '-->') // "- ->" to "-->"
  fixed = fixed.replace(/\s+-{4,}\s+/g, ' --- ') // Multiple dashes to three

  // Fix 3: Ensure flowchart has direction if missing
  fixed = fixed.replace(/^flowchart\s*$/m, 'flowchart TD')
  fixed = fixed.replace(/^flowchart\s*\n/m, 'flowchart TD\n')

  // Fix 4: Ensure graph has direction if missing
  fixed = fixed.replace(/^graph\s*$/m, 'graph TD')
  fixed = fixed.replace(/^graph\s*\n/m, 'graph TD\n')

  // Fix 5: Fix sequence diagram participant syntax - remove quotes
  fixed = fixed.replace(/participant\s+([A-Za-z0-9_]+)\s+as\s+"([^"]+)"/g, 'participant $1 as $2')
  fixed = fixed.replace(/actor\s+([A-Za-z0-9_]+)\s+as\s+"([^"]+)"/g, 'actor $1 as $2')

  // Fix 6: Remove any HTML-like tags that LLMs sometimes add
  fixed = fixed.replace(/<[^>]*>/g, '')

  // Fix 7: Fix quotes in labels - Mermaid prefers no quotes or specific formatting
  fixed = fixed.replace(/\["([^"]+)"\]/g, '[$1]')
  fixed = fixed.replace(/\("([^"]+)"\)/g, '($1)')
  fixed = fixed.replace(/\{"([^"]+)"\}/g, '{$1}')

  // Fix 8: Fix node IDs with special characters (replace with underscores)
  fixed = fixed.replace(/([A-Za-z_])([A-Za-z0-9_]*)-([A-Za-z0-9_]+)\[/g, '$1$2_$3[')
  fixed = fixed.replace(/([A-Za-z_])([A-Za-z0-9_]*)\.([A-Za-z0-9_]+)\[/g, '$1$2_$3[')

  // Fix 9: Fix erDiagram relationship syntax issues
  if (fixed.includes('erDiagram')) {
    // Fix relationship lines - ensure proper syntax
    fixed = fixed.replace(/\s+--\s+/g, ' -- ')
    fixed = fixed.replace(/(\w+)\s*\|\|--o\{\s*(\w+)/g, '$1 ||--o{ $2')
    fixed = fixed.replace(/(\w+)\s*\}o--\|\|\s*(\w+)/g, '$1 }o--|| $2')
    fixed = fixed.replace(/(\w+)\s*\|\|--\|\|\s*(\w+)/g, '$1 ||--|| $2')
    fixed = fixed.replace(/(\w+)\s*\}o--o\{\s*(\w+)/g, '$1 }o--o{ $2')
  }

  // Fix 10: Fix state diagram syntax
  if (fixed.includes('stateDiagram')) {
    // Ensure state names don't have spaces
    fixed = fixed.replace(/state\s+"([^"]+)"\s+as\s+([A-Za-z0-9_]+)/g, 'state "$1" as $2')
  }

  // Fix 11: Remove markdown formatting that LLMs sometimes include
  fixed = fixed.replace(/\*\*([^*]+)\*\*/g, '$1') // Bold
  fixed = fixed.replace(/\*([^*]+)\*/g, '$1') // Italic
  fixed = fixed.replace(/__([^_]+)__/g, '$1') // Bold
  fixed = fixed.replace(/_([^_]+)_/g, '$1') // Italic

  // Fix 12: Fix common typos in diagram types
  fixed = fixed.replace(/^sequencediagram/im, 'sequenceDiagram')
  fixed = fixed.replace(/^statediagram-v2/im, 'stateDiagram-v2')
  fixed = fixed.replace(/^statediagram/im, 'stateDiagram')
  fixed = fixed.replace(/^classdiagram/im, 'classDiagram')
  fixed = fixed.replace(/^erdiagram/im, 'erDiagram')

  // Fix 13: Remove trailing colons that cause issues
  fixed = fixed.replace(/:\s*$/gm, '')

  // Fix 14: Fix label text with problematic characters
  fixed = fixed.replace(/\[([^\]]*[`'"][^\]]*)\]/g, (match, label) => {
    return '[' + label.replace(/[`'"]/g, '') + ']'
  })

  // Fix 15: Remove common unicode characters that cause issues
  fixed = fixed.replace(/[\u2018\u2019]/g, "'") // Smart single quotes
  fixed = fixed.replace(/[\u201C\u201D]/g, '"') // Smart double quotes
  fixed = fixed.replace(/[\u2013\u2014]/g, '-') // En/Em dashes
  fixed = fixed.replace(/\u2026/g, '...') // Ellipsis

  // Fix 16: Fix empty node definitions
  fixed = fixed.replace(/\[\s*\]/g, '[Node]')
  fixed = fixed.replace(/\(\s*\)/g, '(Node)')
  fixed = fixed.replace(/\{\s*\}/g, '{Node}')

  // Fix 17: Fix double arrows or malformed arrows
  fixed = fixed.replace(/--+>/g, '-->')
  fixed = fixed.replace(/-\.+->/g, '-.->')
  fixed = fixed.replace(/=+>/g, '==>')

  // Fix 18: Remove lines that are just dashes or equals
  fixed = fixed.split('\n').filter(line => {
    const trimmed = line.trim()
    return !/^[-=]{2,}$/.test(trimmed)
  }).join('\n')

  // Fix 19: Fix subgraph labels
  fixed = fixed.replace(/subgraph\s+"([^"]+)"/g, 'subgraph $1')

  // Fix 20: Ensure no empty lines at start (after diagram type)
  const fixedLines = fixed.split('\n')
  let result = [fixedLines[0]]
  let foundContent = false
  for (let i = 1; i < fixedLines.length; i++) {
    const line = fixedLines[i]
    if (!foundContent && line.trim() === '') continue
    foundContent = true
    result.push(line)
  }
  fixed = result.join('\n')

  return fixed.trim()
}

// Pre-validate mermaid code before attempting to render
async function validateMermaidCode(code) {
  if (!code || typeof code !== 'string') {
    return { valid: false, error: 'No code provided' }
  }

  const trimmed = code.trim()
  const lines = trimmed.split('\n')

  // Check minimum requirements
  if (lines.length < 2) {
    return { valid: false, error: 'Diagram too short' }
  }

  // Check first line is a valid diagram type
  const firstLine = lines[0].trim().toLowerCase()
  const validStarts = ['flowchart', 'graph', 'sequencediagram', 'statediagram', 'classdiagram', 'erdiagram', 'pie', 'gantt', 'gitgraph']
  if (!validStarts.some(start => firstLine.startsWith(start))) {
    return { valid: false, error: 'Invalid diagram type' }
  }

  // Try to parse
  try {
    await mermaid.parse(trimmed)
    return { valid: true, error: null }
  } catch (parseError) {
    return { valid: false, error: parseError.message || 'Parse failed' }
  }
}

// Helper to render with timeout and retry
async function renderWithTimeout(id, code, timeoutMs = 5000) {
  // First, validate the code looks reasonable
  const lines = code.trim().split('\n')
  if (lines.length < 2) {
    throw new Error('Diagram code too short - needs at least diagram type and content')
  }

  // Pre-validate the syntax before rendering to prevent Mermaid error UI
  const validation = await validateMermaidCode(code)
  if (!validation.valid) {
    throw new Error(`Invalid syntax: ${validation.error}`)
  }

  return Promise.race([
    mermaid.render(id, code),
    new Promise((_, reject) =>
      setTimeout(() => reject(new Error('Rendering timeout - diagram may have invalid syntax')), timeoutMs)
    )
  ])
}

// Try to create a simpler fallback diagram if the original fails
function createFallbackDiagram(originalCode) {
  // Extract just the first line to get diagram type
  const firstLine = originalCode.trim().split('\n')[0]

  if (firstLine.startsWith('flowchart') || firstLine.startsWith('graph')) {
    return `${firstLine}
    subgraph Diagram
        A[Component 1] --> B[Component 2]
        B --> C{Decision}
        C -->|Option 1| D[Action A]
        C -->|Option 2| E[Action B]
        D --> F[Result]
        E --> F
    end

    %% Note: Original diagram had syntax errors - this is a simplified version`
  }

  if (firstLine.startsWith('sequenceDiagram')) {
    return `sequenceDiagram
    autonumber
    participant Client
    participant Service
    participant Database

    Client->>Service: Request
    Service->>Database: Query
    Database-->>Service: Data
    Service-->>Client: Response

    %% Note: Original diagram had syntax errors - this is a simplified version`
  }

  if (firstLine.startsWith('stateDiagram')) {
    return `stateDiagram-v2
    [*] --> Initial
    Initial --> Processing
    Processing --> Complete: Success
    Processing --> Error: Failure
    Complete --> [*]
    Error --> Initial: Retry

    %% Note: Original diagram had syntax errors - this is a simplified version`
  }

  return null
}

export default function MermaidDiagram({ chart, isDark }) {
  const containerRef = useRef(null)
  const [svg, setSvg] = useState('')
  const [error, setError] = useState(null)
  const [isRendering, setIsRendering] = useState(true)
  const [isFullscreen, setIsFullscreen] = useState(false)
  const [zoomLevel, setZoomLevel] = useState(1)
  const renderAttempted = useRef(false)

  // Clean up any Mermaid error elements from the DOM
  useEffect(() => {
    const cleanupMermaidErrors = () => {
      // Remove SVGs with error role
      document.querySelectorAll('svg[aria-roledescription="error"]').forEach(el => {
        el.remove()
      })

      // Remove any orphaned Mermaid error displays
      const errorSelectors = [
        '[id^="dmermaid"]',
        '.mermaid-error',
        '#mermaid-container-error',
        '.error-icon',
        '.error-text',
        'text.error-text',
        'g.error-icon'
      ]
      document.querySelectorAll(errorSelectors.join(', ')).forEach(el => {
        el.remove()
      })

      // Remove any element containing "Syntax error in text" or "mermaid version"
      document.querySelectorAll('body > div, body > svg').forEach(el => {
        const text = el.textContent || ''
        if (text.includes('Syntax error') || text.includes('mermaid version')) {
          el.remove()
        }
      })

      // Remove any fixed position elements that contain mermaid errors
      document.querySelectorAll('body > div').forEach(el => {
        const style = window.getComputedStyle(el)
        if (style.position === 'fixed' || style.position === 'absolute') {
          const text = el.textContent || ''
          if (text.includes('mermaid') || text.includes('Syntax error')) {
            el.remove()
          }
        }
      })
    }

    // Run cleanup on mount and periodically
    cleanupMermaidErrors()
    const interval = setInterval(cleanupMermaidErrors, 500)

    return () => {
      clearInterval(interval)
      cleanupMermaidErrors()
    }
  }, [])

  // Close fullscreen on Escape key - must be before any early returns
  useEffect(() => {
    const handleEscape = (e) => {
      if (e.key === 'Escape' && isFullscreen) {
        setIsFullscreen(false)
        setZoomLevel(1)
      }
    }
    window.addEventListener('keydown', handleEscape)
    return () => window.removeEventListener('keydown', handleEscape)
  }, [isFullscreen])

  useEffect(() => {
    // Reset state when chart changes
    setSvg('')
    setError(null)
    setIsRendering(true)
    renderAttempted.current = false

    const renderDiagram = async () => {
      if (!chart) {
        setError('No diagram code provided')
        setIsRendering(false)
        return
      }

      // Prevent double renders
      if (renderAttempted.current) return
      renderAttempted.current = true

      try {
        // Clean the chart code
        const cleanChart = cleanMermaidCode(chart)

        if (!cleanChart) {
          setError('Invalid diagram code - no valid Mermaid syntax found')
          setIsRendering(false)
          return
        }

        // Early validation - check syntax before attempting render
        const preValidation = await validateMermaidCode(cleanChart)
        if (!preValidation.valid) {
          // Try to use fallback diagram instead
          const fallback = createFallbackDiagram(cleanChart)
          if (fallback) {
            const fallbackValidation = await validateMermaidCode(fallback)
            if (!fallbackValidation.valid) {
              setError(`Diagram syntax error: ${preValidation.error}`)
              setIsRendering(false)
              return
            }
            // Continue with fallback
            console.log('Using fallback diagram due to syntax errors')
          } else {
            setError(`Diagram syntax error: ${preValidation.error}`)
            setIsRendering(false)
            return
          }
        }

        // Update theme based on dark mode - also suppress errors
        mermaid.initialize({
          startOnLoad: false,
          theme: isDark ? 'dark' : 'default',
          securityLevel: 'loose',
          logLevel: 'fatal',
          suppressErrorRendering: true,
          themeVariables: {
            fontSize: '14px',
            fontFamily: 'ui-sans-serif, system-ui, -apple-system, sans-serif',
          },
          flowchart: {
            useMaxWidth: true,
            htmlLabels: true,
            curve: 'basis'
          }
        })

        // Generate unique ID
        const id = `mermaid-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`

        // Render with 5 second timeout
        let result
        try {
          result = await renderWithTimeout(id, cleanChart, 5000)
        } catch (firstError) {
          console.warn('First render attempt failed:', firstError.message)

          // Try with fallback diagram
          const fallback = createFallbackDiagram(cleanChart)
          if (fallback) {
            const fallbackId = `mermaid-fallback-${Date.now()}`
            try {
              result = await renderWithTimeout(fallbackId, fallback, 3000)
              console.log('Fallback diagram rendered successfully')
            } catch (fallbackError) {
              throw firstError // Throw original error if fallback also fails
            }
          } else {
            throw firstError
          }
        }

        if (result && result.svg) {
          setSvg(result.svg)
          setIsRendering(false)
        } else {
          throw new Error('Mermaid returned empty result')
        }
      } catch (err) {
        console.error('Mermaid rendering error:', err)
        setError(err.message || 'Failed to render diagram')
        setIsRendering(false)

        // Immediately cleanup any error elements Mermaid may have created
        setTimeout(() => {
          document.querySelectorAll('svg[aria-roledescription="error"]').forEach(el => el.remove())
          document.querySelectorAll('body > div, body > svg').forEach(el => {
            const text = el.textContent || ''
            if (text.includes('Syntax error') || text.includes('mermaid version')) {
              el.remove()
            }
          })
        }, 0)
      }
    }

    // Small delay to ensure DOM is ready
    const timer = setTimeout(renderDiagram, 100)

    return () => {
      clearTimeout(timer)
    }
  }, [chart, isDark])

  if (error) {
    return (
      <div className={`p-4 rounded-lg border ${
        isDark ? 'bg-red-900/20 border-red-700 text-red-300' : 'bg-red-50 border-red-300 text-red-700'
      }`}>
        <p className="text-sm font-medium">⚠️ Diagram Error</p>
        <p className="text-xs mt-1">{error}</p>
        <details className="mt-2">
          <summary className="text-xs cursor-pointer">Show diagram code</summary>
          <pre className="text-xs mt-2 overflow-x-auto whitespace-pre-wrap">{chart}</pre>
        </details>
      </div>
    )
  }

  if (isRendering) {
    return (
      <div className={`p-8 rounded-lg border ${
        isDark ? 'bg-gray-800 border-gray-700' : 'bg-gray-50 border-gray-300'
      } flex items-center justify-center`}>
        <div className="flex items-center gap-2">
          <svg className="animate-spin h-4 w-4" viewBox="0 0 24 24">
            <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" fill="none"/>
            <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"/>
          </svg>
          <span className="text-sm">Rendering diagram...</span>
        </div>
      </div>
    )
  }

  if (!svg) {
    return null
  }

  const handleZoomIn = () => {
    setZoomLevel(prev => Math.min(prev + 0.25, 3))
  }

  const handleZoomOut = () => {
    setZoomLevel(prev => Math.max(prev - 0.25, 0.5))
  }

  const handleResetZoom = () => {
    setZoomLevel(1)
  }

  const toggleFullscreen = () => {
    setIsFullscreen(!isFullscreen)
    setZoomLevel(1) // Reset zoom when toggling fullscreen
  }

  // Diagram content component
  const DiagramContent = ({ inFullscreen = false }) => (
    <div
      className={`transition-transform duration-200 ${inFullscreen ? 'p-8' : ''}`}
      style={{ transform: `scale(${zoomLevel})`, transformOrigin: 'center top' }}
      dangerouslySetInnerHTML={{ __html: svg }}
    />
  )

  // Control buttons component
  const Controls = ({ inFullscreen = false }) => (
    <div className={`flex items-center gap-1 ${inFullscreen ? 'mb-4' : 'mb-2'}`}>
      <button
        onClick={handleZoomOut}
        disabled={zoomLevel <= 0.5}
        className={`p-1.5 rounded transition-colors ${
          isDark
            ? 'hover:bg-gray-700 disabled:opacity-30 text-gray-300'
            : 'hover:bg-gray-200 disabled:opacity-30 text-gray-600'
        }`}
        title="Zoom out"
      >
        <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M20 12H4" />
        </svg>
      </button>
      <span className={`text-xs px-2 min-w-[3rem] text-center ${isDark ? 'text-gray-400' : 'text-gray-500'}`}>
        {Math.round(zoomLevel * 100)}%
      </span>
      <button
        onClick={handleZoomIn}
        disabled={zoomLevel >= 3}
        className={`p-1.5 rounded transition-colors ${
          isDark
            ? 'hover:bg-gray-700 disabled:opacity-30 text-gray-300'
            : 'hover:bg-gray-200 disabled:opacity-30 text-gray-600'
        }`}
        title="Zoom in"
      >
        <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4v16m8-8H4" />
        </svg>
      </button>
      <button
        onClick={handleResetZoom}
        className={`p-1.5 rounded transition-colors ${
          isDark
            ? 'hover:bg-gray-700 text-gray-300'
            : 'hover:bg-gray-200 text-gray-600'
        }`}
        title="Reset zoom"
      >
        <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" />
        </svg>
      </button>
      <div className={`w-px h-4 mx-1 ${isDark ? 'bg-gray-600' : 'bg-gray-300'}`} />
      <button
        onClick={toggleFullscreen}
        className={`p-1.5 rounded transition-colors ${
          isDark
            ? 'hover:bg-gray-700 text-gray-300'
            : 'hover:bg-gray-200 text-gray-600'
        }`}
        title={inFullscreen ? "Exit fullscreen" : "View fullscreen"}
      >
        {inFullscreen ? (
          <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
          </svg>
        ) : (
          <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 8V4m0 0h4M4 4l5 5m11-1V4m0 0h-4m4 0l-5 5M4 16v4m0 0h4m-4 0l5-5m11 5l-5-5m5 5v-4m0 4h-4" />
          </svg>
        )}
      </button>
    </div>
  )

  return (
    <>
      {/* Normal inline diagram */}
      <div
        ref={containerRef}
        className={`mermaid-diagram p-4 rounded-lg border ${
          isDark ? 'bg-gray-800 border-gray-700' : 'bg-white border-gray-300'
        }`}
      >
        <Controls />
        <div className="overflow-auto max-h-[500px]">
          <DiagramContent />
        </div>
      </div>

      {/* Fullscreen modal */}
      {isFullscreen && (
        <div
          className="fixed inset-0 z-50 flex items-start justify-center overflow-auto"
          style={{ backgroundColor: isDark ? 'rgba(0,0,0,0.95)' : 'rgba(255,255,255,0.98)' }}
          onClick={(e) => {
            if (e.target === e.currentTarget) toggleFullscreen()
          }}
        >
          <div className={`w-full max-w-6xl mx-4 my-8 p-6 rounded-xl shadow-2xl ${
            isDark ? 'bg-gray-800 border border-gray-700' : 'bg-white border border-gray-200'
          }`}>
            <div className="flex items-center justify-between mb-4">
              <h3 className={`text-lg font-semibold ${isDark ? 'text-white' : 'text-gray-900'}`}>
                📊 Diagram View
              </h3>
              <Controls inFullscreen />
            </div>
            <div className="overflow-auto max-h-[80vh] flex items-center justify-center">
              <DiagramContent inFullscreen />
            </div>
            <div className={`mt-4 text-center text-xs ${isDark ? 'text-gray-500' : 'text-gray-400'}`}>
              Press <kbd className={`px-1.5 py-0.5 rounded ${isDark ? 'bg-gray-700' : 'bg-gray-100'}`}>Esc</kbd> or click outside to close
            </div>
          </div>
        </div>
      )}
    </>
  )
}
